### ISSUE TITLE
Internal server error if attribute name has a `-` in it

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya-module-forms#10]
### What steps will reproduce the problem?

1. Create a new form
2. Add a new field
3. Write in the attribute field and press space
4. Space gets converted to `-` and this results in an error but `_` works fine

![image](https://user-images.githubusercontent.com/3450438/103344228-48ac6080-4a8e-11eb-8c23-5278d18f8cd8.png)
> `contact_reason` works but not with `-asdasd` added

### What is the expected result?

Either `-` should be or allowed the space should be converted to `_` instead of `-`

**Comment by nadar** [comment]
This is already fixed in #9 

I am going to release now, thanks
